azure:
  user: vincent.carluer@cosmotech.com
  tenant: cosmotech.com
platform:
  url: https://dev.api.cosmotech.com/v2
  scope: http://dev.api.cosmotech.com
options:
  fetch_from_azure_ad: true
  fallback_admin: vincent.carluer@cosmotech.com
#   Uncomment the line below and define it if you have to migrate only one organization with id
#  organizationId: o-k0re8koklp4g
mapping:
  3a869905-e9f5-4851-a7a9-3079aad49dff: "vincent.carluer@cosmotech.com"
